# .air.toml
# Путь до исходных файлов
[build]
cmd = "go run main.go"
bin = "main"

# Игнорируем файлы, которые не должны пересобираться
[build.exclude]
files = ["assets", "vendor"]

# Время ожидания изменений в исходных файлах
[watch]
interval = "100ms"